version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BoardSize=3
      - ConnectionStrings__Postgres=Host=db;Database=tictactoe;Username=postgres;Password=12345
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tictactoe
    ports:
      - "5432:5432"
